# 🔒 Private Vulnerability Reporting Configuration

# Private vulnerability reporting'i etkinleştir
private_vulnerability_reporting:
  enabled: true

  # Güvenlik açığı bildirimi için form ayarları
  form:
    # Form başlığı
    title: '🔒 Güvenlik Açığı Bildirimi'

    # Form açıklaması
    description: |
      Bu form aracılığıyla güvenlik açıklarını güvenli bir şekilde bildirebilirsiniz.
      Tüm bildirimler gizli tutulur ve güvenlik ekibimiz tarafından incelenir.

    # Gerekli alanlar
    required_fields:
      - 'vulnerability_type'
      - 'severity'
      - 'description'
      - 'reproduction_steps'
      - 'impact'
      - 'contact_email'

    # Opsiyonel alanlar
    optional_fields:
      - 'affected_components'
      - 'browser_info'
      - 'os_info'
      - 'screenshots'
      - 'additional_info'

    # Güvenlik açığı türleri
    vulnerability_types:
      - 'authentication_bypass'
      - 'authorization_bypass'
      - 'data_exposure'
      - 'sql_injection'
      - 'xss'
      - 'csrf'
      - 'rce'
      - 'privilege_escalation'
      - 'information_disclosure'
      - 'rate_limiting_bypass'
      - 'input_validation'
      - 'other'

    # Güvenlik seviyeleri
    severity_levels:
      - 'critical'
      - 'high'
      - 'medium'
      - 'low'

    # Yanıt süreleri
    response_times:
      critical: '24h'
      high: '48h'
      medium: '72h'
      low: '1w'

# Güvenlik açığı yönetim süreci
vulnerability_management:
  # Bildirim alındığında
  on_report:
    # Otomatik bildirim
    notifications:
      - type: 'email'
        recipients:
          - 'security@i-ep.app'
        template: 'vulnerability_report_received'

      - type: 'slack'
        channel: '#security'
        template: 'vulnerability_report_received'

    # Otomatik etiketleme
    auto_labeling:
      enabled: true
      labels:
        - 'security'
        - 'vulnerability'
        - 'needs-review'

    # Otomatik atama
    auto_assignment:
      enabled: true
      assignees:
        - 'tural-musab'

    # Güvenlik ekibi bildirimi
    security_team_notification:
      enabled: true
      team: 'security-team'
      priority: 'high'

# Güvenlik açığı araştırma süreci
investigation_process:
  # İlk değerlendirme
  initial_assessment:
    timeframe: '24h'
    required_actions:
      - 'severity_assessment'
      - 'reproduction_attempt'
      - 'impact_analysis'

  # Detaylı araştırma
  detailed_investigation:
    timeframe: '72h'
    required_actions:
      - 'root_cause_analysis'
      - 'affected_components_identification'
      - 'exploitation_scenario_analysis'
      - 'mitigation_strategy_development'

# Çözüm süreci
resolution_process:
  # Güvenlik yaması geliştirme
  patch_development:
    timeframe: '7d'
    required_actions:
      - 'security_patch_development'
      - 'testing'
      - 'code_review'
      - 'documentation_update'

  # Yayınlama
  release:
    timeframe: '14d'
    required_actions:
      - 'security_advisory_creation'
      - 'patch_release'
      - 'user_notification'
      - 'monitoring'

# İletişim ayarları
communication:
  # Güvenlik açığı bildirimi yapan kişi ile iletişim
  reporter_communication:
    enabled: true
    channels:
      - 'email'
      - 'github_issues'

    # Otomatik güncellemeler
    auto_updates:
      enabled: true
      events:
        - 'investigation_started'
        - 'patch_development_started'
        - 'patch_released'
        - 'resolution_completed'

  # İç ekip iletişimi
  internal_communication:
    enabled: true
    channels:
      - 'slack'
      - 'email'
      - 'github_issues'

    # Kritik güvenlik açıkları için acil bildirim
    emergency_notifications:
      enabled: true
      severity_threshold: 'high'
      channels:
        - 'slack'
        - 'email'
        - 'sms'

# Güvenlik açığı kategorileri
vulnerability_categories:
  # Kimlik doğrulama ve yetkilendirme
  authentication:
    - 'authentication_bypass'
    - 'session_management'
    - 'password_reset'
    - 'mfa_bypass'

  # Veri güvenliği
  data_security:
    - 'data_exposure'
    - 'data_leakage'
    - 'sensitive_data_disclosure'
    - 'encryption_issues'

  # Web güvenliği
  web_security:
    - 'sql_injection'
    - 'xss'
    - 'csrf'
    - 'open_redirect'
    - 'ssrf'

  # Sistem güvenliği
  system_security:
    - 'rce'
    - 'privilege_escalation'
    - 'file_upload'
    - 'command_injection'

  # API güvenliği
  api_security:
    - 'api_authentication'
    - 'api_authorization'
    - 'rate_limiting_bypass'
    - 'input_validation'

# Güvenlik açığı şablonları
vulnerability_templates:
  # SQL Injection şablonu
  sql_injection:
    title: 'SQL Injection Vulnerability'
    description: 'SQL injection vulnerability in [component]'
    reproduction_steps:
      - 'Navigate to [URL]'
      - 'Enter malicious SQL payload in [field]'
      - 'Submit the form'
      - 'Observe unauthorized data access'
    impact: 'Unauthorized access to database, potential data breach'

  # XSS şablonu
  xss:
    title: 'Cross-Site Scripting (XSS) Vulnerability'
    description: 'XSS vulnerability in [component]'
    reproduction_steps:
      - 'Navigate to [URL]'
      - 'Enter malicious JavaScript in [field]'
      - 'Submit the form'
      - 'Observe script execution'
    impact: 'Session hijacking, data theft, malicious code execution'

  # Authentication Bypass şablonu
  auth_bypass:
    title: 'Authentication Bypass Vulnerability'
    description: 'Authentication bypass in [component]'
    reproduction_steps:
      - 'Navigate to [URL]'
      - 'Bypass authentication using [method]'
      - 'Access protected resource'
    impact: 'Unauthorized access to protected resources'

# Güvenlik açığı ödül programı
bug_bounty:
  # Ödül programı durumu
  enabled: false # Gelecekte etkinleştirilecek

  # Ödül miktarları
  rewards:
    critical: '$1000'
    high: '$500'
    medium: '$200'
    low: '$50'

  # Ödül kriterleri
  criteria:
    - 'First valid report'
    - 'Clear reproduction steps'
    - 'Detailed impact analysis'
    - 'Responsible disclosure'

# Güvenlik açığı istatistikleri
statistics:
  # İstatistik toplama
  enabled: true

  # Toplanan metrikler
  metrics:
    - 'total_reports'
    - 'resolved_reports'
    - 'average_resolution_time'
    - 'severity_distribution'
    - 'category_distribution'

  # Raporlama
  reporting:
    frequency: 'monthly'
    recipients:
      - 'security@i-ep.app'
      - 'management@i-ep.app'

# Entegrasyonlar
integrations:
  # Jira entegrasyonu
  jira:
    enabled: false
    project_key: 'SEC'
    issue_type: 'Bug'
    custom_fields:
      severity: 'customfield_10001'
      category: 'customfield_10002'

  # Slack entegrasyonu
  slack:
    enabled: true
    webhook_url: '${{ secrets.SLACK_SECURITY_WEBHOOK }}'
    channel: '#security'

  # Email entegrasyonu
  email:
    enabled: true
    smtp_server: 'smtp.gmail.com'
    from_address: 'security@i-ep.app'
    to_addresses:
      - 'security@i-ep.app'
      - 'tural-musab'

# Güvenlik açığı bildirimi formu
vulnerability_form:
  # Form alanları
  fields:
    # Güvenlik açığı türü
    vulnerability_type:
      type: 'select'
      required: true
      options:
        - 'Authentication Bypass'
        - 'Authorization Bypass'
        - 'Data Exposure'
        - 'SQL Injection'
        - 'Cross-Site Scripting (XSS)'
        - 'Cross-Site Request Forgery (CSRF)'
        - 'Remote Code Execution (RCE)'
        - 'Privilege Escalation'
        - 'Information Disclosure'
        - 'Rate Limiting Bypass'
        - 'Input Validation'
        - 'Other'

    # Güvenlik seviyesi
    severity:
      type: 'select'
      required: true
      options:
        - 'Critical'
        - 'High'
        - 'Medium'
        - 'Low'

    # Açıklama
    description:
      type: 'textarea'
      required: true
      placeholder: 'Güvenlik açığının detaylı açıklaması...'

    # Reprodüksiyon adımları
    reproduction_steps:
      type: 'textarea'
      required: true
      placeholder: 'Güvenlik açığını reprodüksiyon etmek için adımlar...'

    # Etki analizi
    impact:
      type: 'textarea'
      required: true
      placeholder: 'Bu güvenlik açığının potansiyel etkisi...'

    # İletişim email'i
    contact_email:
      type: 'email'
      required: true
      placeholder: 'your-email@example.com'

    # Etkilenen bileşenler
    affected_components:
      type: 'text'
      required: false
      placeholder: 'Etkilenen bileşenler (opsiyonel)...'

    # Tarayıcı bilgisi
    browser_info:
      type: 'text'
      required: false
      placeholder: 'Tarayıcı ve versiyon (opsiyonel)...'

    # İşletim sistemi bilgisi
    os_info:
      type: 'text'
      required: false
      placeholder: 'İşletim sistemi (opsiyonel)...'

    # Ek bilgiler
    additional_info:
      type: 'textarea'
      required: false
      placeholder: 'Ek bilgiler (opsiyonel)...'

# Güvenlik açığı yanıt şablonları
response_templates:
  # Bildirim alındı yanıtı
  report_received:
    subject: 'Güvenlik Açığı Bildirimi Alındı - #{report_id}'
    body: |
      Merhaba,

      Güvenlik açığı bildiriminiz başarıyla alınmıştır.

      **Bildirim ID:** #{report_id}
      **Güvenlik Seviyesi:** #{severity}
      **Tür:** #{vulnerability_type}

      Güvenlik ekibimiz bu bildirimi inceleyecek ve size en kısa sürede yanıt verecektir.

      Teşekkürler,
      Güvenlik Ekibi
      i-ep.app

  # Araştırma başladı yanıtı
  investigation_started:
    subject: 'Güvenlik Açığı Araştırması Başladı - #{report_id}'
    body: |
      Merhaba,

      Güvenlik açığı bildiriminiz (#{report_id}) araştırma aşamasına geçmiştir.

      **Mevcut Durum:** Araştırma
      **Tahmini Süre:** #{estimated_time}

      Size araştırma sonuçları hakkında bilgi vereceğiz.

      Teşekkürler,
      Güvenlik Ekibi
      i-ep.app

  # Çözüm tamamlandı yanıtı
  resolution_completed:
    subject: 'Güvenlik Açığı Çözüldü - #{report_id}'
    body: |
      Merhaba,

      Güvenlik açığı bildiriminiz (#{report_id}) başarıyla çözülmüştür.

      **Çözüm:** #{resolution_details}
      **Yayınlanan Versiyon:** #{release_version}

      Güvenlik açığını bildirdiğiniz için teşekkür ederiz.

      Teşekkürler,
      Güvenlik Ekibi
      i-ep.app
